controller_list:
 - name: darwin/left_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j_shoulder_l
      - j_high_arm_l
      - j_low_arm_l
      - j_wrist_l
      - j_gripper_l

 - name: darwin/right_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j_shoulder_r
      - j_high_arm_r
      - j_low_arm_r
      - j_wrist_r
      - j_gripper_r

 - name: darwin/left_leg_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j_pelvis_l
      - j_thigh1_l
      - j_thigh2_l
      - j_tibia_l
      - j_ankle1_l
      - j_ankle2_l

 - name: darwin/right_leg_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j_pelvis_r
      - j_thigh1_r
      - j_thigh2_r
      - j_tibia_r
      - j_ankle1_r
      - j_ankle2_r

 - name: darwin/head_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j_pan
      - j_tilt
