controller_list:
  - name: fake_right_arm_controller
    joints:
      - j_shoulder_r
      - j_high_arm_r
      - j_low_arm_r
  - name: fake_left_arm_controller
    joints:
      - j_shoulder_l
      - j_high_arm_l
      - j_low_arm_l