# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j_high_arm_l:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0
  j_high_arm_r:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0
  j_low_arm_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_low_arm_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_shoulder_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_shoulder_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0